language: go

os:
  - linux

dist: focal

go:
  - 1.9.x

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      sudo apt update -yy;
      sudo apt install libtcod-dev libsdl2-dev pkg-config -yy;
    fi

install:
  - go get -t ./...
