language: go

os:
  - linux

dist: focal

go:
  - 1.9.x

env:
  - CGO_CFLAGS=-I/usr/include/libtcod

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      sudo apt update -yy;
      sudo apt install libtcod-dev libsdl2-dev -yy;
    fi

install:
  - go get -t ./...
