language: go

os:
  - linux

dist: focal

go:
  - 1.9.x

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      sudo apt update -yy;
      sudo apt install libtcod-dev libsdl2-dev pkg-config -yy;
      export CGO_CFLAGS=$(pkg-config libtcod sdl2 --cflags);
      export CGO_LDFLAGS=$(pkg-config libtcod sdl2 --ldflags);
    fi

install:
  - go get -t ./...
