language: go

os:
  - linux

dist: focal

go:
  - 1.9.x

env:
  - CGO_CFLAGS=$(pkg-config libtcod sdl2 --cflags)
  - CGO_LDFLAGS=$(pkg-config libtcod sdl2 --ldflags)

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      sudo apt update -yy;
      sudo apt install libtcod-dev libsdl2-dev pkg-config -yy;
    fi

install:
  - go get -t ./...
