package tcod

func convertRune(r rune) byte {
	switch r {
	case CharSmiley:
		return byte(1)
	case CharSmileyInv:
		return byte(2)
	case CharHeart:
		return byte(3)
	case CharDiamond:
		return byte(4)
	case CharClub:
		return byte(5)
	case CharSpade:
		return byte(6)
	case CharBullet:
		return byte(7)
	case CharBulletActive:
		return byte(8)
	case CharBulletInv:
		return byte(9)
	case CharBulletInvActive:
		return byte(10)
	case CharMale:
		return byte(11)
	case CharFemale:
		return byte(12)
	case CharNote:
		return byte(13)
	case CharDoubleNote:
		return byte(14)
	case CharStar:
		return byte(15)
	case CharTriangleArrowR:
		return byte(16)
	case CharTriangleArrowL:
		return byte(17)
	case CharDoubleArrowV:
		return byte(18)
	case CharDoubleExclamation:
		return byte(19)
	case CharPilcrow:
		return byte(20)
	case CharLamp:
		return byte(21)
	case CharUnderBlock:
		return byte(22)
	case CharDoubleArrowVertUnderscore:
		return byte(23)
	case CharArrowUp:
		return byte(24)
	case CharArrowDown:
		return byte(25)
	case CharArrowRight:
		return byte(26)
	case CharArrowLeft:
		return byte(27)
	case CharRightAngle:
		return byte(28)
	case CharDoubleArrowH:
		return byte(29)
	case CharTriangleArrowU:
		return byte(30)
	case CharTriangleArrowD:
		return byte(31)
	case CharHouse:
		return byte(127)
	case CharUpperCedilla:
		return byte(128)
	case CharULowermlaut:
		return byte(129)
	case CharELowerAcute:
		return byte(130)
	case CharALowerCaret:
		return byte(131)
	case CharALowerUmlaut:
		return byte(132)
	case CharALowerGrave:
		return byte(133)
	case CharALowerCircle:
		return byte(134)
	case CharLowerCedilla:
		return byte(135)
	case CharELowerCaret:
		return byte(136)
	case CharELowerUmlaut:
		return byte(137)
	case CharELowerGrave:
		return byte(138)
	case CharILowerUmlaut:
		return byte(139)
	case CharILowerCaret:
		return byte(140)
	case CharILowerGrave:
		return byte(141)
	case CharAUpperUmlaut:
		return byte(142)
	case CharAUpperCircle:
		return byte(143)
	case CharEUpperAcute:
		return byte(144)
	case CharAELower:
		return byte(145)
	case CharAEUpper:
		return byte(146)
	case CharOLowerCaret:
		return byte(147)
	case CharOLowerUmlaut:
		return byte(148)
	case CharOLowerGrave:
		return byte(149)
	case CharULowerCaret:
		return byte(150)
	case CharULowerGrave:
		return byte(151)
	case CharYLowerUmlaut:
		return byte(152)
	case CharOUpperUmlaut:
		return byte(153)
	case CharUUpperUmlaut:
		return byte(154)
	case CharCent:
		return byte(155)
	case CharPound:
		return byte(156)
	case CharYen:
		return byte(157)
	case CharPoint:
		return byte(158)
	case CharFunction:
		return byte(159)
	case CharALowerAcute:
		return byte(160)
	case CharILowerAccute:
		return byte(161)
	case CharOLowerAccute:
		return byte(162)
	case CharULowerAccute:
		return byte(163)
	case CharNTildeLower:
		return byte(164)
	case CharNTildeUpper:
		return byte(165)
	case CharExpA:
		return byte(166)
	case CharExpO:
		return byte(167)
	case CharInvQuestion:
		return byte(168)
	case CharLogicalNot:
		return byte(169)
	case CharLogicalNotInv:
		return byte(170)
	case CharHalf:
		return byte(171)
	case CharQuarter:
		return byte(172)
	case CharInvExclamation:
		return byte(173)
	case CharDoubleArrowL:
		return byte(174)
	case CharDoubleArrowR:
		return byte(175)
	case CharBlock1:
		return byte(176)
	case CharBlock2:
		return byte(177)
	case CharBlock3:
		return byte(178)
	case CharWallV:
		return byte(179)
	case CharTeeW:
		return byte(180)
	case CharTeeHDoubleW:
		return byte(181)
	case CharTeeVDoubleW:
		return byte(182)
	case CharCornerVDoubleNE:
		return byte(183)
	case CharCornerHDoubleNE:
		return byte(184)
	case CharTeeDoubleW:
		return byte(185)
	case CharWallDoubleV:
		return byte(186)
	case CharCornerDoubleNE:
		return byte(187)
	case CharCornerDoubleSE:
		return byte(188)
	case CharCornerVDoubleSE:
		return byte(189)
	case CharCornerHDoubleSE:
		return byte(190)
	case CharCornerNE:
		return byte(191)
	case CharCornerSW:
		return byte(192)
	case CharTeeN:
		return byte(193)
	case CharTeeS:
		return byte(194)
	case CharTeeE:
		return byte(195)
	case CharWallH:
		return byte(196)
	case CharWallCross:
		return byte(197)
	case CharTeeHDoubleE:
		return byte(198)
	case CharTeeVDoubleE:
		return byte(199)
	case CharCornerDoubleSW:
		return byte(200)
	case CharCornerDoubleNW:
		return byte(201)
	case CharTeeDoubleN:
		return byte(202)
	case CharTeeDoubleS:
		return byte(203)
	case CharTeeDoubleE:
		return byte(204)
	case CharWallDoubleH:
		return byte(205)
	case CharWallDoubleCross:
		return byte(206)
	case CharTeeHDoubleN:
		return byte(207)
	case CharTeeVDoubleN:
		return byte(208)
	case CharTeeHDoubleS:
		return byte(209)
	case CharTeeVDoubleS:
		return byte(210)
	case CharCornerVDoubleSW:
		return byte(211)
	case CharCornerHdoubleSW:
		return byte(212)
	case CharCornerHDoubleNW:
		return byte(213)
	case CharCornerVDoubleNW:
		return byte(214)
	case CharWallVDoubleCross:
		return byte(215)
	case CharWallHDoubleCross:
		return byte(216)
	case CharCornerSE:
		return byte(217)
	case CharCornerNW:
		return byte(218)
	case CharBlock4:
		return byte(219)
	case CharSubpDown:
		return byte(220)
	case CharSubpLeft:
		return byte(221)
	case CharSubpRight:
		return byte(222)
	case CharSubpUp:
		return byte(223)
	case CharAlpha:
		return byte(224)
	case CharBeta:
		return byte(225)
	case CharGamma:
		return byte(226)
	case CharPi:
		return byte(227)
	case CharSigmaUpper:
		return byte(228)
	case CharSigmaLower:
		return byte(229)
	case CharMi:
		return byte(230)
	case CharTau:
		return byte(231)
	case CharPhiUpper:
		return byte(232)
	case CharTheta:
		return byte(233)
	case CharOmega:
		return byte(234)
	case CharDelta:
		return byte(235)
	case CharInfinite:
		return byte(236)
	case CharPhiLower:
		return byte(237)
	case CharEpsilon:
		return byte(238)
	case CharArc:
		return byte(239)
	case CharList:
		return byte(240)
	case CharPlusMinus:
		return byte(241)
	case CharGreaterEqual:
		return byte(242)
	case CharLowerEqual:
		return byte(243)
	case CharIntegralUp:
		return byte(244)
	case CharIntegralDown:
		return byte(245)
	case CharDivision:
		return byte(246)
	case CharAlmostEqual:
		return byte(247)
	case CharDegree:
		return byte(248)
	case CharDot1:
		return byte(249)
	case CharDot2:
		return byte(250)
	case CharRoot:
		return byte(251)
	case CharExpN:
		return byte(252)
	case CharExp2:
		return byte(253)
	case CharSquare:
		return byte(254)
	case CharSquareInv:
		return byte(255)
	default:
		return byte(r)
	}
}
