#!/usr/bin/awk -f

BEGIN   {
    print "package tmap\n" > OFILE
    print "// #include <libtcod.h>" > OFILE
    print "import \"C\" " > OFILE
    print "\ntype FovType int\n" > OFILE
    print "var (" > OFILE
        }
        { printf "\tFov%s FovType = C.FOV_%s\n", $1, toupper($1) > OFILE }
END     {
    print ")" > OFILE
}
