#!/usr/bin/awk -f

BEGIN {
        cname[0] = ""
        cname[1] = "BKGND_"
        cname[2] = "RENDERER_"

        gname[0] = "Alignment"
        gname[1] = "BgFlag"
        gname[2] = "Renderer"

        prefix[0] = "Align"
        prefix[1] = "Bg"
        prefix[2] = "Render"

        print "package tcod" > OFILE
        print "\n" > OFILE
        print "// #include <libtcod.h>" > OFILE
        print "import \"C\"" > OFILE

        for (i = 0; i < 3; i++)
          printf "type %s int\n", gname[i] > OFILE

        print "\n" > OFILE
        print "var (" > OFILE
        i = 0
      }

/^$/  {
        print ")\n\nvar (" > OFILE
        i++
      }

      {
        if ($1)
          printf "\t%s%s %s = C.TCOD_%s%s\n", prefix[i], $1, gname[i], cname[i], toupper($1) > OFILE
      }

END   { print ")" > OFILE }
